menu:
  首页: /
  归档: /archives
  分类: /categories
  标签: /tags

# gitment
gitment: true
gitment_owner: daitra@sina.com
gitment_repo: Gitment
gitment_client_id: b8322cc969e5b18107f5
gitment_client_secret: f6aa8f1ec7d89022049e40ffdec3e7087a1f07d2

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId:
